type Event {
  id: Int!
  garden: Garden
  name: String
  area: Float
  cost: Float
}

input registerEventInput {
  name: String!
  gardenId: Int!
  area: Float!
  cost: Float!
}

input updateEventInput{
  id: Int!
  name: String!
  area: Float!
  cost: Float!
}

input destroyEventInput{
  id: Int!
}

type Query {
  event(id: Int): Event
}

type Mutation {
  registerEvent(input: registerEventInput): Event @auth(requires: [WORKER])
  updateEvent(input: updateEventInput): Boolean @auth(requires: [WORKER])
  destroyEvent(input: destroyEventInput): Boolean @auth(requires: [WORKER])
}