type Garden {
  id: Int!
  name: String
  farm: Farm
}

input registerGardenInput {
  name: String!
}

input updateGardenInput {
  id: Int!
  name: String!
}

input destroyGardenInput {
  id: Int!
}

type Query {
  garden(id: Int): Garden
}

type Mutation {
  registerGarden(input: registerGardenInput): Garden @auth(requires: [OWNER])
  updateGarden(input: updateGardenInput): Boolean @auth(requires: [OWNER])
  destroyGarden(input: destroyGardenInput): Boolean @auth(requires: [OWNER])
}
