directive @auth(requires: [Type] = [ADMIN]) on OBJECT | FIELD_DEFINITION

enum Type {
  ADMIN
  OWNER
  WORKER
}

enum Gender {
  MALE
  FEMALE
}

type User {
  id: Int!
  firstName: String!
  lastName: String!
  email: String!
  password: String
  type: Type!
  gender: Gender
  age: Int
}

type Token {
  id: String
  expiresIn: Int
}

input registerUserWithEmailInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  type: Type!
  gender: Gender
  age: Int
}

input loginUserWithEmailInput {
  email: String!
  password: String!
}

type Query {
  user(id: Int!): User
  # users(offset: Int, limit: Int): [User]
}

type Mutation {
  registerUserWithEmail(input: registerUserWithEmailInput): User
  loginWithEmail(input: loginUserWithEmailInput): Token
}
