type Farm {
  id: Int!
  name: String
  location: String
  owner: User
}

input createFarmInput {
  name: String!
  location: String!
}

input updateFarmInput{
  id: Int!
  name: String!
  location: String!
}

type Query {
  farm(id: Int): Farm
}

type Mutation {
  createFarm(input: createFarmInput): Farm @auth(requires: [OWNER])
  updateFarm(input: updateFarmInput): Boolean @auth(requires: [OWNER])
}
